{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"heart_2022_no_nans\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "es-PA",
    "cultures": [
      {
        "name": "es-PA",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "es-PA",
    "tables": [
      {
        "name": "heart_2022_no_nans",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dedfd982-9f7e-486a-9618-022db289fbaa",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Sex",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "006d6497-6f15-45b7-b088-5cf22cae59eb",
            "sourceColumn": "Sex",
            "summarizeBy": "none"
          },
          {
            "name": "GeneralHealth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2bee88a-ce48-4213-a607-7cd5cd7bbf62",
            "sourceColumn": "GeneralHealth",
            "summarizeBy": "none"
          },
          {
            "name": "PhysicalHealthDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e632544f-8bd2-4ae7-abd3-98a0a165c1a2",
            "sourceColumn": "PhysicalHealthDays",
            "summarizeBy": "sum"
          },
          {
            "name": "MentalHealthDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a19a45c3-45b8-453a-953a-2ec498ac5be3",
            "sourceColumn": "MentalHealthDays",
            "summarizeBy": "sum"
          },
          {
            "name": "LastCheckupTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e511bfdf-15a4-4901-9c38-fff48601ae74",
            "sourceColumn": "LastCheckupTime",
            "summarizeBy": "none"
          },
          {
            "name": "PhysicalActivities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d86e9965-eb1b-4b23-aecf-5bd9a315500e",
            "sourceColumn": "PhysicalActivities",
            "summarizeBy": "none"
          },
          {
            "name": "SleepHours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef4c45e7-3c9f-49c8-a1a0-750d0770dd4f",
            "sourceColumn": "SleepHours",
            "summarizeBy": "sum"
          },
          {
            "name": "RemovedTeeth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d222eece-9459-424a-b26e-b41dce36185b",
            "sourceColumn": "RemovedTeeth",
            "summarizeBy": "none"
          },
          {
            "name": "HadHeartAttack",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9fe70a70-a97b-4a86-a1d3-347e31205985",
            "sourceColumn": "HadHeartAttack",
            "summarizeBy": "none"
          },
          {
            "name": "HadAngina",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "63197bb2-7709-4719-a810-573cabe99e37",
            "sourceColumn": "HadAngina",
            "summarizeBy": "none"
          },
          {
            "name": "HadStroke",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "747cd9b0-96be-491e-86ac-45a78ab30c77",
            "sourceColumn": "HadStroke",
            "summarizeBy": "none"
          },
          {
            "name": "HadAsthma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2eb5daf6-7e33-48c9-a50a-059f00e1f9e7",
            "sourceColumn": "HadAsthma",
            "summarizeBy": "none"
          },
          {
            "name": "HadSkinCancer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "858a1f53-ae0c-4978-a632-d1e94b84bca2",
            "sourceColumn": "HadSkinCancer",
            "summarizeBy": "none"
          },
          {
            "name": "HadCOPD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e96e563b-68df-4c9f-8186-a63daf47dfef",
            "sourceColumn": "HadCOPD",
            "summarizeBy": "none"
          },
          {
            "name": "HadDepressiveDisorder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "13a380c4-c878-48bf-ae54-80822b6da882",
            "sourceColumn": "HadDepressiveDisorder",
            "summarizeBy": "none"
          },
          {
            "name": "HadKidneyDisease",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ab5e28a2-06cf-44e5-9789-3ca9464f916c",
            "sourceColumn": "HadKidneyDisease",
            "summarizeBy": "none"
          },
          {
            "name": "HadArthritis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2ba01f45-3467-4d0d-81eb-7bc009f60cb1",
            "sourceColumn": "HadArthritis",
            "summarizeBy": "none"
          },
          {
            "name": "HadDiabetes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7cbff37c-7373-4b07-9240-83f87f8981ec",
            "sourceColumn": "HadDiabetes",
            "summarizeBy": "none"
          },
          {
            "name": "DeafOrHardOfHearing",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24ed2c01-477d-4336-895d-41527f47547b",
            "sourceColumn": "DeafOrHardOfHearing",
            "summarizeBy": "none"
          },
          {
            "name": "BlindOrVisionDifficulty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24413902-1586-41cc-a638-9616e347e6ec",
            "sourceColumn": "BlindOrVisionDifficulty",
            "summarizeBy": "none"
          },
          {
            "name": "DifficultyConcentrating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c864be58-a7c4-4fbd-854a-8ace9654e97f",
            "sourceColumn": "DifficultyConcentrating",
            "summarizeBy": "none"
          },
          {
            "name": "DifficultyWalking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25a088bf-854d-47d4-b5bf-9dcd67ef5749",
            "sourceColumn": "DifficultyWalking",
            "summarizeBy": "none"
          },
          {
            "name": "DifficultyDressingBathing",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b2bbd7c-3fd4-4c86-8f18-24ecd127cc92",
            "sourceColumn": "DifficultyDressingBathing",
            "summarizeBy": "none"
          },
          {
            "name": "DifficultyErrands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d95c98d9-0438-4481-a51c-8fa35d29179f",
            "sourceColumn": "DifficultyErrands",
            "summarizeBy": "none"
          },
          {
            "name": "SmokerStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af54fbe4-90a8-4ecf-896c-19ff8e3811ac",
            "sourceColumn": "SmokerStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ECigaretteUsage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d7828f4-c6d6-4691-8705-5d547f32137b",
            "sourceColumn": "ECigaretteUsage",
            "summarizeBy": "none"
          },
          {
            "name": "ChestScan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3221d315-ad9a-407c-ac0a-43090a80f077",
            "sourceColumn": "ChestScan",
            "summarizeBy": "none"
          },
          {
            "name": "RaceEthnicityCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bd6a5f3-fc92-4031-8773-f60f2788695e",
            "sourceColumn": "RaceEthnicityCategory",
            "summarizeBy": "none"
          },
          {
            "name": "AgeCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13ec9055-f0e9-4d59-be87-e9458c62c928",
            "sourceColumn": "AgeCategory",
            "summarizeBy": "none"
          },
          {
            "name": "HeightInMeters",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "065390bd-7043-4640-9e40-7e7401d61d54",
            "sourceColumn": "HeightInMeters",
            "summarizeBy": "sum"
          },
          {
            "name": "WeightInKilograms",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "266a8986-3d28-40f3-b7e2-33ebd0e1d602",
            "sourceColumn": "WeightInKilograms",
            "summarizeBy": "sum"
          },
          {
            "name": "BMI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0f528adb-1eee-4732-886b-0959210fc033",
            "sourceColumn": "BMI",
            "summarizeBy": "sum"
          },
          {
            "name": "AlcoholDrinkers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de2dda2d-308a-498a-a17e-e41c880317a8",
            "sourceColumn": "AlcoholDrinkers",
            "summarizeBy": "none"
          },
          {
            "name": "HIVTesting",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eeea3946-ddcb-456b-8fd4-2806f083f246",
            "sourceColumn": "HIVTesting",
            "summarizeBy": "none"
          },
          {
            "name": "FluVaxLast12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f2a4222-fad2-4c1b-8906-e2c7ceac6349",
            "sourceColumn": "FluVaxLast12",
            "summarizeBy": "none"
          },
          {
            "name": "PneumoVaxEver",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2878d01-f90c-4e76-bbd8-0b3473d9689b",
            "sourceColumn": "PneumoVaxEver",
            "summarizeBy": "none"
          },
          {
            "name": "TetanusLast10Tdap",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "597ff94f-36b0-4a9c-81fb-38561e12d297",
            "sourceColumn": "TetanusLast10Tdap",
            "summarizeBy": "none"
          },
          {
            "name": "HighRiskLastYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c70f498-2f4f-4a41-a17e-b454afb26fb0",
            "sourceColumn": "HighRiskLastYear",
            "summarizeBy": "none"
          },
          {
            "name": "CovidPos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29c41eb8-25c9-4a2a-9533-9fd62cfb16f6",
            "sourceColumn": "CovidPos",
            "summarizeBy": "none"
          },
          {
            "name": "HadHeartAttack_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadHeartAttack]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadHeartAttack]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9245a00b-c896-4865-938e-8692d7c195d2",
            "type": "calculated"
          },
          {
            "name": "HadAngina_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadAngina]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadAngina]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "29e8564f-e3cb-4b4b-ba2d-660102936297",
            "type": "calculated"
          },
          {
            "name": "HadStroke_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadStroke]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadStroke]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3a65cdba-0f7e-4744-a8a8-1fb38f50ad7a",
            "type": "calculated"
          },
          {
            "name": "HadAsthma_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadAsthma]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadAsthma]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ad3637a8-4847-4be1-9696-a3ac66a8b8e0",
            "type": "calculated"
          },
          {
            "name": "HadSkinCancer_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadSkinCancer]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadSkinCancer]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ef177db7-cbd2-481d-a1c9-036f73d64756",
            "type": "calculated"
          },
          {
            "name": "HadCOPD_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadCOPD]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadCOPD]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a87f5b09-595c-4b03-8c9b-7a876e51ffe3",
            "type": "calculated"
          },
          {
            "name": "HadDepressiveDisorder_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadDepressiveDisorder]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadDepressiveDisorder]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0700e8c8-6f5f-4e4a-8c3f-892e1d0f8178",
            "type": "calculated"
          },
          {
            "name": "HadKidneyDisease_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadKidneyDisease]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadKidneyDisease]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "bf1c66a0-24c8-4982-bdc1-3cbca7b99d0a",
            "type": "calculated"
          },
          {
            "name": "HadArthritis_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadArthritis]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadArthritis]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "00393cd3-b8a6-41f4-ba8f-073f93fbbd20",
            "type": "calculated"
          },
          {
            "name": "HadDiabetes_Bool",
            "dataType": "int64",
            "expression": "IF(UPPER('heart_2022_no_nans'[HadDiabetes]) = \"YES\", 1, IF(UPPER('heart_2022_no_nans'[HadDiabetes]) = \"NO\", 0, BLANK()))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "98445599-187c-4879-9420-6bf5a7dc91d9",
            "type": "calculated"
          },
          {
            "name": "BMI_Category",
            "dataType": "string",
            "expression": [
              "",
              "    SWITCH(",
              "        TRUE(),",
              "        'heart_2022_no_nans'[BMI] < 18.5, \"Bajo Peso\",",
              "        'heart_2022_no_nans'[BMI] >= 18.5 && 'heart_2022_no_nans'[BMI] < 25, \"Normal\",",
              "        'heart_2022_no_nans'[BMI] >= 25 && 'heart_2022_no_nans'[BMI] < 30, \"Sobrepeso\",",
              "        'heart_2022_no_nans'[BMI] >= 30, \"Obesidad\"",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "a800e16a-7119-4e8e-ae6b-9779b9d42d2f",
            "type": "calculated"
          },
          {
            "name": "Health_Risk",
            "dataType": "string",
            "expression": [
              "",
              "    IF(",
              "        'heart_2022_no_nans'[HadHeartAttack] = \"Yes\" || ",
              "        'heart_2022_no_nans'[HadStroke] = \"Yes\" || ",
              "        'heart_2022_no_nans'[HadDiabetes] = \"Yes\" || ",
              "        'heart_2022_no_nans'[HadCOPD] = \"Yes\", \"Alto Riesgo\", \"Bajo Riesgo\"",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "cbdf5679-2f08-4614-9b48-232eb274bac4",
            "type": "calculated"
          },
          {
            "name": "Active_Status",
            "dataType": "string",
            "expression": [
              "",
              "    IF('heart_2022_no_nans'[PhysicalActivities] = \"Yes\", \"Activo\", \"Sedentario\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "aa397f0b-40ac-4cd9-9d5d-3d5280d84682",
            "type": "calculated"
          }
        ],
        "lineageTag": "d92ce5f1-7ed7-4ba8-bc4b-bcceded1001b",
        "measures": [
          {
            "name": "Avg_Sleep_Hours",
            "expression": [
              "",
              "    AVERAGE('heart_2022_no_nans'[SleepHours])"
            ],
            "formatString": "0.00",
            "lineageTag": "8c3541b6-545c-409a-964d-41b4d311f6b4"
          },
          {
            "name": "%Vaccinated",
            "expression": [
              "",
              "    DIVIDE(",
              "        COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[FluVaxLast12] = \"Yes\")),",
              "        COUNTROWS('heart_2022_no_nans')",
              "    )"
            ],
            "formatString": "0.00%",
            "lineageTag": "1ceab3c3-f1a4-4d1c-a27e-250e44e38aa2"
          },
          {
            "name": "%HadHeartAttack",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadHeartAttack] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "db7f7dbc-916a-4f4d-ac91-7b2de1201d77"
          },
          {
            "name": "%HadAngina",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadAngina] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "cbfd5e29-03d9-49c5-95f8-1ffc6eaf5c68"
          },
          {
            "name": "%HadStroke",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadStroke] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "d20d0f18-86c3-4cab-a3d0-34f97d4958f2"
          },
          {
            "name": "%HadAsthma",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadAsthma] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "35784b21-9e31-43b0-8499-a0ae10070223"
          },
          {
            "name": "%HadSkinCancer",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadSkinCancer] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "834bd4ba-a21b-4a79-b25e-47fffe1a5c41"
          },
          {
            "name": "%HadCOPD",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadCOPD] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "3aca6785-fe3a-4989-991b-e54563e15e55"
          },
          {
            "name": "%HadDepressiveDisorder",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadDepressiveDisorder] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "c1c22b13-9773-405f-8e4b-fb1f64415c78"
          },
          {
            "name": "%HadKidneyDisease",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadKidneyDisease] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "c2d40c01-86c5-468d-b9a2-b33d7ba5145d"
          },
          {
            "name": "%HadArthritis",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadArthritis] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "87a024cb-33d9-4516-be4f-2331fe981a2f"
          },
          {
            "name": "%HadDiabetes",
            "expression": [
              "",
              "            DIVIDE(",
              "                COUNTROWS(FILTER('heart_2022_no_nans', 'heart_2022_no_nans'[HadDiabetes] = \"Yes\")),",
              "                COUNTROWS('heart_2022_no_nans')",
              "            )"
            ],
            "formatString": "0.00%",
            "lineageTag": "a2980541-ea01-4e41-9ccc-f6bc9b648bee"
          }
        ],
        "partitions": [
          {
            "name": "heart_2022_no_nans",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(File.Contents(\"C:\\Users\\ariel\\Documents\\Data Viz\\HealthDataViz\\heart_2022_no_nans.csv\"),[Delimiter=\",\", Columns=40, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"State\", type text}, {\"Sex\", type text}, {\"GeneralHealth\", type text}, {\"PhysicalHealthDays\", Int64.Type}, {\"MentalHealthDays\", Int64.Type}, {\"LastCheckupTime\", type text}, {\"PhysicalActivities\", type text}, {\"SleepHours\", Int64.Type}, {\"RemovedTeeth\", type text}, {\"HadHeartAttack\", type text}, {\"HadAngina\", type text}, {\"HadStroke\", type text}, {\"HadAsthma\", type text}, {\"HadSkinCancer\", type text}, {\"HadCOPD\", type text}, {\"HadDepressiveDisorder\", type text}, {\"HadKidneyDisease\", type text}, {\"HadArthritis\", type text}, {\"HadDiabetes\", type text}, {\"DeafOrHardOfHearing\", type text}, {\"BlindOrVisionDifficulty\", type text}, {\"DifficultyConcentrating\", type text}, {\"DifficultyWalking\", type text}, {\"DifficultyDressingBathing\", type text}, {\"DifficultyErrands\", type text}, {\"SmokerStatus\", type text}, {\"ECigaretteUsage\", type text}, {\"ChestScan\", type text}, {\"RaceEthnicityCategory\", type text}, {\"AgeCategory\", type text}, {\"HeightInMeters\", type number}, {\"WeightInKilograms\", type number}, {\"BMI\", type number}, {\"AlcoholDrinkers\", type text}, {\"HIVTesting\", type text}, {\"FluVaxLast12\", type text}, {\"PneumoVaxEver\", type text}, {\"TetanusLast10Tdap\", type text}, {\"HighRiskLastYear\", type text}, {\"CovidPos\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}